import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

import "primereact/resources/themes/saga-blue/theme.css"; // Tema PrimeReact
import "primereact/resources/primereact.min.css"; // Gaya dasar PrimeReact
import "primeicons/primeicons.css";

export const metadata = {
  icons: {
    icon: "/gambar/newLogo.png",
  },
  title: "STHG Tasikmalaya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
